config/routes.rb
Rails.application.routes.draw do

    root 'users#home'
    get 'users/login' => 'users#login', as: :login
    post 'users/login' => 'users#auth', as: :auth
    post 'users/send' => 'users#sendmsg', as: :send
    post 'users/logout' => 'users#logout', as: :logout
    get 'users/received' => 'users#refreshmsg', as: :received
    get 'users/sent' => 'users#refreshsent', as: :sent
    resources :users ,only: [:create,:new,:show,:destroy]
    

end

app/models/message.rb
class Message < ActiveRecord::Base
	before_save :add_sent_time
	belongs_to :sender,class_name: "User",foreign_key: "sender_id"
	belongs_to :recipient, class_name: "User", foreign_key: "recipient_id"

	private
	def add_sent_time
		self.sent_at=Time.current
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sent_messages, class_name: "Message",foreign_key: "sender_id"
	has_many :received_messages, class_name: "Message",foreign_key: "recipient_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end

	def create
		@user=User.new(users_params)
		if @user.save
			redirect_to root_path
		else
			redirect_to new_user_path,danger: "Unable to add user"
		end
	end

	def login
	end
	
	def destroy
	end

	def auth
		user_name=params[:user_name]
		user=User.find_by(user_name: user_name)
		if(user!=nil)
			if user.password==params[:password]
				session[:loggedin]=true
				session[:userid]=user.id 
				redirect_to root_path
			else	redirect_to login_path, danger: "Invalid details"
			end
		else
			redirect_to login_path, danger: "Invalid user"
		end
	end

	def home
		if (session[:loggedin]!=true) then redirect_to login_path
		else
			@user=User.find(session[:userid])
		end
	end

	def show
		if session[:loggedin]!=true then redirect_to lopgin_path
		elsif session[:userid]==params[:id]
			@user=User.find(session[:userid])
		else
			redirect_to root_path
		end
	end

	def sendmsg
		if session[:loggedin]!=true then redirect_to lopgin_path end
		@message=Message.new
		@message.sender=User.find(session[:userid])
		@message.recipient=User.find(params[:user][:id])
		@message.body=params[:body]
		if @message.save then @response="Success"
		else
			@response="Unable to send"
		end
	end
	
	def logout
		session[:loggedin]=false
		session[:userid]=nil
		redirect_to login_path
	end

	def refreshmsg
		@user=User.find(session[:userid])
		respond_to do |format|
			format.html {render :layout =>false}
		end
	end

	def refreshsent
		@user=User.find(session[:userid])
		respond_to do |format|
			format.html {render :layout =>false}
		end
	end

	private
	def users_params
		params.require(:user).permit(:name,:user_name,:password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messageapp - <%= yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="status" style="display:none;" >
</div>
<% if session[:loggedin]==true then %>
<%= button_to  "Logout",logout_path %>
<% end %>
<%= yield  %>

</body>
</html>

app/views/messages/_message.html.erb
	<div class="msg">
	<span class="from">From: <%=message.sender.name %></span> <span class="to" > To : <%= message.recipient.name %> </span>  <span class="time"> at <%= message.sent_at %> </span> <br/>
	<%= message.body %>
	<hr/>
	</div>

app/views/users/home.html.erb
<% provide(:title,"Home") %>
<h1>Home page </h1>

Welcome user <%= @user.name %>

<br/>
Your messages :
<%= link_to "Received","#",onclick: "switchTo(1)" %>
<%= link_to "Sent", "#",onclick: "switchTo(2)" %>
<div id="receivedmessages" >

<%= render @user.received_messages %>

</div>

<div id="sentmessages" style="display:none;">
<%= render @user.sent_messages %>
</div>
<div class="form" >
<%= form_tag send_path,remote: true do %>
	<%= label_tag "To :"%>
	<%= select("user", "id", User.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}) %>
	<br/>
	<%= label_tag "Message" %>
	<%= text_area_tag :body %>
	<br/>
	<%= submit_tag "Send" %>
<% end %>
</div>
<%= javascript_tag do %>
	function refresh()
	{
		$.ajax({
	  url: '<%= received_path %>',
	  type: 'GET',
	  success: function(data) {
		//called when successful
		$("#receivedmessages").html(data);
	  },
	  error: function(e) {
		//called when there is an error
		//console.log(e.message);
		alert("Error :"+e.message);
  		}
	});
	$.ajax({
		  url: '<%= sent_path %>',
		  type: 'GET',
		  success: function(data) {
			//called when successful
			$('#sentmessages').html(data);
		  },
		  error: function(e) {
			//called when there is an error
			//console.log(e.message);
			alert("Error "+e.message);
		  }
		});
	}

	function switchTo(option)
	{
		if(option==1)//Display the received messages
		{
			$("#sentmessages").hide();
			$("#receivedmessages").show();
		}
		else //Display sent messages
		{
			$("#receivedmessages").hide();
			$("#sentmessages").show();
		}

	}

	setInterval(refresh,7000);

<% end %>

app/views/users/login.html.erb
<% provide :title,"Login" %>
<h1>Enter your credentials</h1>
<%= form_tag auth_path, method: 'post' do%>
  <%= label_tag :user_name, "Username:" %>
  <%= text_field_tag :user_name %>
  <br/>
  <%= label_tag :password , "Password :" %>
  <%= password_field_tag :password %>
  <br/>

  <%= submit_tag "Login" %>
<% end %>
<%= link_to "New user ?", new_user_path %>

app/views/users/new.html.erb
<% provide :title,'Add user ' %>

<h1>Register New User </h1>
<%= form_for @user do |f| %>
 <h2>Enter your details</h2>
 <br/>
 <%= f.label :name %>
 <%= f.text_field :name %><br/>

 <%= f.label :user_name %>
 <%= f.text_field :user_name %>
 <br/>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <br/>

 <%= f.submit "Submit" %>


<% end %>

app/views/users/refreshmsg.html.erb
<%= render @user.received_messages %>

app/views/users/refreshsent.html.erb
<%= render @user.sent_messages %>

app/views/users/sendmsg.js.erb
$("#status").html("<%= @response %>");
$("#status").slideDown(3000).delay(2000).fadeOut(200);
$("#body").val("");
$("#user[id]").val("");

app/views/users/show.html.erb
<% provide :title , "Show" %>
<h1> User page</h1>
Name :<%= @user.name %>
<br/>
Username :<%= @user.user_name %>